version: '3'
services:
  database:
    build: ./postgres
    container_name: postgres
    networks:
      - local
    expose:
      - "5432"
    ports:
      - "5432:5432"
  
  server:
    build: ./api
    container_name: bidyourauction
    networks:
      - local
    volumes:
      - "./api"
    expose:
      - "5000"
    ports:
      - "8080:5000"
    depends_on:
      - database
networks:
  local:
    driver: bridge